spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/userrole?allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
    username: root
    password: 3s5a6dslipknot
  flyway:
    enabled: true
  jpa:
    show_sql: true
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect